worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    map $upstream_addr $backend_name {
    "10.7.11.131:3001" A;
    "10.7.11.144:3002" B;
    	}

    upstream app_backend {
        server 10.7.11.131:3001;
        server 10.7.11.144:3002;
    }

    server {
        listen 443 ssl;
        server_name 10.7.11.79;

        ssl_certificate /Users/neerajsingh/nginx-certs/server.crt;
        ssl_certificate_key /Users/neerajsingh/nginx-certs/server.key;

        location / {
            proxy_pass http://app_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root html;
        }
    }
    server {
    	listen 8443 ssl;
    	http2 on;

    	server_name app.noaa.test api.noaa.test;

    	ssl_certificate /Users/neerajsingh/LoadBalancingSubmission/05_TLS/certs/server.crt;
    	ssl_certificate_key /Users/neerajsingh/LoadBalancingSubmission/05_TLS/certs/server.key;

    	ssl_protocols TLSv1.2 TLSv1.3;

    	location / {
        	proxy_pass http://app_backend;

        	proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;

    }
}
}
